galaxyservers:
  hosts:
    galaxy-umsa.grid.cesnet.cz:
      ansible_user: galaxy
    usegalaxy.cz:
      ansible_user: galaxy-cz
    galaxy-qa1.galaxy.cloud.e-infra.cz:
      ansible_user: debian
    galaxy-qa2.galaxy.cloud.e-infra.cz:
      ansible_user: debian
    repeatexplorer-elixir.cerit-sc.cz:
      ansible_user: galaxy

dbservers:
  children: galaxyservers

production:
  hosts:
    usegalaxy.cz:
      ansible_user: galaxy-cz
    galaxy-umsa.grid.cesnet.cz:
      ansible_user: galaxy
    repeatexplorer-elixir.cerit-sc.cz:
      ansible_user: galaxy

cloudservers:
  hosts:
    galaxy-qa1.galaxy.cloud.e-infra.cz:
      ansible_user: debian
    galaxy-qa2.galaxy.cloud.e-infra.cz:
      ansible_user: debian
