# Galaxy, Postgres, Nginx
- src: galaxyproject.galaxy
  version: 0.10.14
- src: galaxyproject.nginx
  version: 0.7.1
- src: galaxyproject.postgresql
  version: 1.1.2
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: galaxyproject.miniconda
  version: 0.3.1
- src: usegalaxy_eu.certbot
  version: 0.1.11
# gxadmin (used in cleanup, and later monitoring.)
- src: galaxyproject.gxadmin
  version: 0.0.12
# TUS (uploads)
- name: galaxyproject.tusd
  version: 0.0.1
# TPV Linting
- name: usegalaxy_eu.tpv_auto_lint
  version: 0.4.4
# RabbitMQ for Pulsar
- src: geerlingguy.docker
  version: 6.1.0
- src: usegalaxy_eu.rabbitmqserver
  version: 1.4.4
# Our FTP Server
- src: galaxyproject.proftpd
  version: 0.3.1
# Celery, Redis, and Flower (dashboard)
- name: geerlingguy.redis
  version: 1.8.0
- name: usegalaxy_eu.flower
  version: 1.0.2
