---
- name: Ensure group exists
  ansible.builtin.group:
    name: "{{ flower_group }}"
    state: present

- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ flower_user }}"
    groups: ["{{ flower_group }}"]
    append: yes

- name: Check if the app directory exists
  ansible.builtin.find:
    paths: "{{ flower_app_dir }}"
    file_type: directory
  register: appdir

- name: Empty app directory
  ansible.builtin.fail:
    msg: "Directory {{ flower_app_dir }} is empty or missing."
  when: appdir is defined and appdir.matched <= 0 and flower_app_dir != ""

- name: Ensure log directory exists
  tags: [flower, dirs]
  file:
    state: touch
    path: "{{ flower_log_file }}"
    owner: "{{ flower_user }}"
    group: "{{ flower_user }}"
    mode: 0755

- name: Ensure config directory exists
  tags: [flower, dirs]
  file:
    state: directory
    path: "{{ flower_conf_dir }}"
    owner: root
    group: root
    mode: 0755

- name: Ensure Python3 and pip is installed
  ansible.builtin.package:
    name:
      - "{{ flower_python_version }}"
      - "{{ flower_pip_version }}"
      - virtualenv
    state: present

- name: Install virtualenv
  ansible.builtin.pip:
    name: virtualenv

- name: Ensure venv directory exists
  tags: [flower, dirs]
  file:
    state: directory
    path: "{{ flower_venv_dir }}"
    owner: root
    group: root
    mode: 0755

- name: Ensure Python Flower package is installed
  tags: [flower, python, pip]
  pip:
    name: "{{ flower_python_package_name }}"
    version: "{{ flower_python_package_version }}"
    virtualenv: "{{ flower_venv_dir }}"
    virtualenv_python: "{{ flower_python_main }}"
    state: present

- name: Ensure Flower configuration file is correct
  tags: [flower, config]
  template:
    src: flowerconfig.py.j2
    dest: "{{ flower_conf_dir }}/flowerconfig.py"
    owner: root
    group: "{{ flower_group }}"
    mode: 0640

- name: Ensure Flower unitfile is correct
  when:
    ansible_os_family: RedHat
  tags: [flower, service, systemd]
  template:
    src: flower.service.j2
    dest: /etc/systemd/system/flower.service
    owner: root
    group: root
    mode: 0644

- name: Enable Flower
  tags: [flower, service]
  ansible.builtin.systemd:
    name: flower
    state: "{{ flower_state }}"
    enabled: "{{ flower_enabled }}"
    daemon_reload: yes
