---

- name: Install the list of LLMs
  copy:
    src: "files/galaxy/genai_models.loc"
    dest: "{{ galaxy_tool_data_path }}/genai_models.loc"

- name: Install specific local dependencies
  pip:
    name: openai
    virtualenv: "{{ galaxy_venv_dir }}"
