---
- name: Add cron job for certbot renewal (if configured).
  ansible.builtin.cron:
    name: Certbot automatic renewal.
    cron_file: "{{ certbot_auto_renew_cron_file | default(omit) }}"
    job: "{{ certbot_script }} renew --quiet {{ '--no-self-upgrade' if 'certbot-auto' in certbot_script else '' }} {{ certbot_auto_renew_extra }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
